// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYa0Rcdff0U7vee6RgBBThIffa-GEwY8',
    appId: '1:661143409008:web:75b3b92372719783667fb5',
    messagingSenderId: '661143409008',
    projectId: 'skilllinkapptest',
    authDomain: 'skilllinkapptest.firebaseapp.com',
    storageBucket: 'skilllinkapptest.firebasestorage.app',
    measurementId: 'G-PNQ18Z0N8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWiHEs9v5Eox4EZh-SnQGJkBo2Qhm4RYo',
    appId: '1:661143409008:android:c20d5c0369f4f376667fb5',
    messagingSenderId: '661143409008',
    projectId: 'skilllinkapptest',
    storageBucket: 'skilllinkapptest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm2a0HeTORFib-OFrxr4jiB8ZB7MuDy28',
    appId: '1:661143409008:ios:1b96e2714aa0ec3a667fb5',
    messagingSenderId: '661143409008',
    projectId: 'skilllinkapptest',
    storageBucket: 'skilllinkapptest.firebasestorage.app',
    iosBundleId: 'com.example.skilllinkAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm2a0HeTORFib-OFrxr4jiB8ZB7MuDy28',
    appId: '1:661143409008:ios:1b96e2714aa0ec3a667fb5',
    messagingSenderId: '661143409008',
    projectId: 'skilllinkapptest',
    storageBucket: 'skilllinkapptest.firebasestorage.app',
    iosBundleId: 'com.example.skilllinkAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWYa0Rcdff0U7vee6RgBBThIffa-GEwY8',
    appId: '1:661143409008:web:6fb0cbc6ee58eaca667fb5',
    messagingSenderId: '661143409008',
    projectId: 'skilllinkapptest',
    authDomain: 'skilllinkapptest.firebaseapp.com',
    storageBucket: 'skilllinkapptest.firebasestorage.app',
    measurementId: 'G-B2DFH4B5H3',
  );
}
